const quize = [
  {
    qid: 1,
    question_en: "",
    question_bn: "পদ্মা সেতুর পাইলিং গভীরতা কত ?",
    options_en: [{ text: "" }, { text: "" }],
    options_bn: [{ text: "৩৮৩ ফুট" }, { text: "৩৮৭ ফুট" }],
    ans_en: "",
    ans_bn: "৩৮৩ ফুট",
    quiz_type: "text",
    quiz_feature_image: "https://i.ibb.co/4mMwpkq/padda-Bridge.png",
  },
  {
    qid: 2,
    question_en: "",
    question_bn: "পদ্মা সেতুর পাইলিং গভীরতা কত ?",
    options_en: [{ text: "" }, { text: "" }],
    options_bn: [{ text: "৩৮৩ ফুট" }, { text: "৩৮৭ ফুট" }],
    ans_en: "",
    ans_bn: "৩৮৩ ফুট",
    quiz_type: "text",
    quiz_feature_image: "https://i.ibb.co/4mMwpkq/padda-Bridge.png",
  },
  {
    qid: 3,
    question_en: "",
    question_bn: "পদ্মা সেতুর পাইলিং গভীরতা কত ?",
    options_en: [{ text: "" }, { text: "" }],
    options_bn: [{ text: "৩৮৩ ফুট" }, { text: "৩৮৭ ফুট" }],
    ans_en: "",
    ans_bn: "৩৮৩ ফুট",
    quiz_type: "text",
    quiz_feature_image: "https://i.ibb.co/4mMwpkq/padda-Bridge.png",
  },

  {
    qid: 4,
    question_en: "",
    question_bn: "এখানে কোনটি সাকিব আল হাসান চোখ ?",
    options_en: [{ text: "" }, { text: "" }],
    options_bn: [
      { text: "https://i.ibb.co/kMj79Yn/sakiboption1.png" },
      { text: "https://i.ibb.co/m56Bhvf/sakiboption2.png" },
    ],
    ans_en: "",
    ans_bn: "https://i.ibb.co/kMj79Yn/sakiboption1.png",
    quiz_type: "image",
    quiz_feature_image: "https://i.ibb.co/W6d8fcB/sakibquiz.png",
  },
  {
    qid: 5,
    question_en: "",
    question_bn: "এখানে কোনটি সাকিব আল হাসান চোখ ?",
    options_en: [{ text: "" }, { text: "" }],
    options_bn: [
      { text: "https://i.ibb.co/kMj79Yn/sakiboption1.png" },
      { text: "https://i.ibb.co/m56Bhvf/sakiboption2.png" },
    ],
    ans_en: "",
    ans_bn: "https://i.ibb.co/kMj79Yn/sakiboption1.png",
    quiz_type: "image",
    quiz_feature_image: "https://i.ibb.co/W6d8fcB/sakibquiz.png",
  },
  {
    qid: 6,
    question_en: "",
    question_bn: "এখানে কোনটি সাকিব আল হাসান চোখ ?",
    options_en: [{ text: "" }, { text: "" }],
    options_bn: [
      { text: "https://i.ibb.co/kMj79Yn/sakiboption1.png" },
      { text: "https://i.ibb.co/m56Bhvf/sakiboption2.png" },
    ],
    ans_en: "",
    ans_bn: "https://i.ibb.co/kMj79Yn/sakiboption1.png",
    quiz_type: "image",
    quiz_feature_image: "https://i.ibb.co/W6d8fcB/sakibquiz.png",
  },
];
