import Head from "next/head";
import BottomHeader from "../Components/BottomHeader/BottomHeader";
import HomePage from "../Components/HomePage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Quizeers</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div>
          <HomePage />
        </div>
      </main>
 
    </div>
  );
}
